on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Login to docker"
        run: docker login --username ${{ secerts.NODE_USERNAME }} --password ${{ secerts.NODE_PASSWORD }} 

      - name: "Building image"
        run: docker build -t ${{secerts.NODE_USERNAME}}/nodeimage .

      - name: "Pushing it to Docker"
        run: docker push ${{secerts.NODE_USERNAME}}/nodeimage

